### PR TITLE
[merge conflicts] update libchdr based on latest upstream

### PR DESCRIPTION
**Pull request by negativeExponent**
May (or may not) fix a few chd-related issues listed below. It doesn't hurt if doesn't fix in any case:

https://github.com/libretro/beetle-pce-fast-libretro/issues/157
https://github.com/libretro/beetle-pce-fast-libretro/issues/129
https://github.com/libretro/beetle-pce-fast-libretro/issues/80

Related libchdr update that fixes at least 1 issue:
https://github.com/libretro/pcsx_rearmed/commit/9c659ffe685d5615b15c31cd86814e597cff7488

Related issue with regards to dependency resync:
https://github.com/rtissera/libchdr/issues/24

### CODE REVIEW

**Comment by negativeExponent** [comment]
mute is more important than this. great.

**Comment by twinaphex** [comment]
@negativeExponent Do not close this. I very much want to merge this but we will first have to make sure that libchdr on both RetroArch and this repo are on the same page. Have some patience please.

**Comment by negativeExponent** [comment]
due to structure changes on upstream, this is probably irrelevant to merge unless updated.

**Comment by negativeExponent** [comment]
update to latest upstream changes, but retains folder structure and filename changes to stil comply to current layout

NOTE: dependencies not updated.

**Comment by negativeExponent** [comment]
im discontinuing this. im gettng merge conflicts now.

**Comment by twinaphex** [comment]
@negativeExponent No worries, @rtissera will make sure libchdr in this and other cores gets updated

**Comment by twinaphex** [comment]
@rtissera can you fix this up?

**Comment by twinaphex** [comment]
Or should it be closed?

**Comment by negativeExponent** [comment]
this is outdated. and core already have merge latest deps and libchdr.

closing this then to avoid confusion.

**Pull request closed without merging**
