### PR TITLE
accurate: add 32-bpp output (optional)

### PR DESCRIPTION
**Pull request by tryal-star**

### CODE REVIEW

**Comment by negativeExponent** [comment]
whats this obsession to change cores to run in 32bit depth?

**Comment by tryal-star** [comment]
I prefer running at 888 to avoid 565 green tint bias. Mednafen upstream usually defaults at 32-bpp also. I know that the difference is very minor but it's something I want.

I made sure everyone gets 16-bpp by default. It won't affect anyone's speed.
https://github.com/libretro/beetle-pce-fast-libretro/pull/131/files#diff-b67911656ef5d18c4ae36cb6741b7965R41


@hizzlekizzle, @twinaphex
If it's becoming a problem for any libretro maintainers, I will stop requesting core modifications.

Note that Beetle Lynx runs at 32-bpp default, and not 16-bpp. But given the above comment, I will refrain from suggesting anything.

**Comment by hizzlekizzle** [comment]
@tryal-star hey, no worries. We appreciate the attention :)

**Comment by twinaphex** [comment]
We appreciate it for sure.

**Pull request merged**
